# Generated by Django 4.0 on 2022-01-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api_clone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsrfToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cookie',
            field=models.CharField(default='', max_length=256),
        ),
    ]
