# Generated by Django 4.0 on 2022-01-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api_clone', '0005_chatroomuserrelation_is_group_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='user_ids',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
