# Generated by Django 4.0 on 2022-01-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api_clone', '0006_chatroom_user_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='is_group_chat',
            new_name='is_group',
        ),
    ]
