# Generated by Django 4.0 on 2022-01-06 16:31

import chat_api_clone.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api_clone', '0007_rename_is_group_chat_chatroom_is_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(default='http://localhost:8000/media/images/logo/chat_default.png', upload_to=chat_api_clone.models.upload_chat_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='http://localhost:8000/media/images/logo/chat_default.png', upload_to=chat_api_clone.models.upload_user_path),
        ),
    ]
